---
title: "Lab6"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Lab6}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(tibble)
library(tidyr)
library(dplyr)

options(dplyr.summarise.inform = FALSE)

smith_example <- tribble(
  -Same, -Different, -Imagery, -Photo, -Placebo,
  #--|--|--|--|----
  25, 11, 14, 25, 
)

aov.out <- aov(DV~IV, Smith_example)
summary(aov.out)

contrasts(smith_example$IV)

c1 <- c(2, -3, 2, 2, -3)
c2 <- c(2, 0, -1, -1, 0)
c3 <- c(0, 0, +1, -2, 0)
c4 <- c(0, +1, 0, 0, -1)

my_contrasts <- cbind(c1, c2, c3, c4)

contrasts(smith_example$IV) <- my_contrasts 

aov.out <- aov(DV~IV, smith_example)
summary(aov.out)

(full_summary <- summary.aov(aov.out,
                             split = list(IV = list("(1+3+4) vs. (2+5)
                                                    "))))
```

###Factor conversion
```{r}
a <- c(1, 1, 2, 2, 3, 3, 4, 4)
class(a)
as.factor(a) -> a
class(a)
```

```{r}
group_means <- c(3, 4, 10, 11)
(grand_mean <- mean(group_means))

contrasts(fake_data$IV)[,'D'] * differences

grand_mean + (1 * differences[4])

contrasts(fake_data$IV)

contrasts(fake_data$IV) * differences

grand_mean * contrasts(fake_dataIV) + contrasts(fake_data$IV) * differences
```

```{r}
c1 <- c(-1, -1, 1, 1)
c2 <- c(1, -1, 0, 0)
c3 <- c()
c4 <- c()
        )
```

```{r}


library(dplyr)
sim_data <- tibble(DV = rnorm(6*100, 0, 1),
                   IV = factor(rep(1:6, each = 100)))
contrasts(sim_data$IV) <- orth_contrasts

A <- replicate(10,000, rbinom(1, 20, 0.05))
hist(A)

length(A[A > 0])/10000

A <- rbinom (10,000, 20, 0.05)
length(A[A >0])/10000

?rbinom
length(A[A > 0])/10000


t_results <- replicate(1000, t.test(rnorm(10, 0, 1), var.equal = TRUE)$p.value)

hist(t_results)
```

```{r setup}
library(DBSStats2Labs)
```
